@extends('layouts.base')

@section('content')
    <div>CardLog</div>
        <tr>									
            <th>種別（ショッピング、キャッシング、その他）</th>
            <th>ご利用年月日</th>
            <th>ご利用場所</th>
            <th>ご利用内容</th>
            <th>ご利用金額</th>
            <th>お支払金額（キャッシングでは利息を含みます）</th>
            <th>支払区分</th>
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
@endsection